### ISSUE TITLE
Compatibility issue with latest Cura version - crashes on save of Cube3 and CubePro files

### ISSUE THREAD

**Issue by dougk12** [mirdoc/Cura-CubePrinterPlugin#14]
This is new after upgrading from 5.10.x to 5.11.0.

Error: A fatal error has occurred in Cura. Please send us the crash report....:

Error traceback:
Traceback (most recent call last):
  File "cura\CuraApplication.py", line 1229, in event
    return super().event(event)
           ^^^^^^^^^^^^^^^^^^^^
  File "UM\Qt\QtApplication.py", line 510, in event
    event._function_event.call()
  File "UM\Event.py", line 218, in call
    self._function(*self._args, **self._kwargs)
  File "cura\Utils\Threading.py", line 34, in _handle_call
    ico.result = func(*args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^
TypeError: CubeproWriter.write() got an unexpected keyword argument 'mime_type'

Logs:
Thread 0x000048ac (most recent call first):
  File "threading.py", line 359 in wait
  File "zeroconf\__init__.py", line 2534 in wait
  File "zeroconf\__init__.py", line 1715 in run
  File "threading.py", line 1073 in _bootstrap_inner
  File "threading.py", line 1030 in _bootstrap

Thread 0x000050ac (most recent call first):
  File "threading.py", line 359 in wait
  File "threading.py", line 655 in wait
  File "C:\Program Files\UltiMaker Cura 5.11.0\share\cura\plugins\UM3NetworkPrinting\src\Network\ZeroConfClient.py", line 83 in _handleOnServiceChangedRequests
  File "threading.py", line 1010 in run
  File "threading.py", line 1073 in _bootstrap_inner
  File "threading.py", line 1030 in _bootstrap

Thread 0x000050bc (most recent call first):
  File "zeroconf\__init__.py", line 1369 in run
  File "threading.py", line 1073 in _bootstrap_inner
  File "threading.py", line 1030 in _bootstrap

Thread 0x00005780 (most recent call first):
  File "C:\Program Files\UltiMaker Cura 5.11.0\share\cura\plugins\RemovableDriveOutputDevice\RemovableDrivePlugin.py", line 61 in _updateThread
  File "threading.py", line 1010 in run
  File "threading.py", line 1073 in _bootstrap_inner
  File "threading.py", line 1030 in _bootstrap

Thread 0x00002994 (most recent call first):
  File "threading.py", line 355 in wait
  File "threading.py", line 507 in acquire
  File "UM\JobQueue.py", line 98 in _nextJob
  File "UM\JobQueue.py", line 124 in run
  File "threading.py", line 1073 in _bootstrap_inner
  File "threading.py", line 1030 in _bootstrap

Thread 0x000054d0 (most recent call first):
  File "threading.py", line 355 in wait
  File "threading.py", line 507 in acquire
  File "UM\JobQueue.py", line 98 in _nextJob
  File "UM\JobQueue.py", line 124 in run
  File "threading.py", line 1073 in _bootstrap_inner
  File "threading.py", line 1030 in _bootstrap

Thread 0x000050dc (most recent call first):
  File "threading.py", line 355 in wait
  File "threading.py", line 507 in acquire
  File "UM\JobQueue.py", line 98 in _nextJob
  File "UM\JobQueue.py", line 124 in run
  File "threading.py", line 1073 in _bootstrap_inner
  File "threading.py", line 1030 in _bootstrap

Thread 0x00000ad0 (most recent call first):
  File "threading.py", line 355 in wait
  File "threading.py", line 655 in wait
  File "cura\Utils\Threading.py", line 39 in _call_on_qt_thread_wrapper
  File "UM\FileHandler\WriteFileJob.py", line 78 in run
  File "UM\JobQueue.py", line 133 in run
  File "threading.py", line 1073 in _bootstrap_inner
  File "threading.py", line 1030 in _bootstrap

Thread 0x00005934 (most recent call first):
  File "threading.py", line 355 in wait
  File "threading.py", line 507 in acquire
  File "UM\JobQueue.py", line 98 in _nextJob
  File "UM\JobQueue.py", line 124 in run
  File "threading.py", line 1073 in _bootstrap_inner
  File "threading.py", line 1030 in _bootstrap

Thread 0x0000047c (most recent call first):
  File "threading.py", line 355 in wait
  File "threading.py", line 507 in acquire
  File "UM\JobQueue.py", line 98 in _nextJob
  File "UM\JobQueue.py", line 124 in run
  File "threading.py", line 1073 in _bootstrap_inner
  File "threading.py", line 1030 in _bootstrap

Thread 0x0000558c (most recent call first):
  File "threading.py", line 355 in wait
  File "threading.py", line 507 in acquire
  File "UM\JobQueue.py", line 98 in _nextJob
  File "UM\JobQueue.py", line 124 in run
  File "threading.py", line 1073 in _bootstrap_inner
  File "threading.py", line 1030 in _bootstrap

Thread 0x0000286c (most recent call first):
  File "threading.py", line 355 in wait
  File "threading.py", line 507 in acquire
  File "UM\JobQueue.py", line 98 in _nextJob
  File "UM\JobQueue.py", line 124 in run
  File "threading.py", line 1073 in _bootstrap_inner
  File "threading.py", line 1030 in _bootstrap

Current thread 0x000010c4 (most recent call first):
  File "cura\CrashHandler.py", line 397 in _logInfoWidget
  File "cura\CrashHandler.py", line 182 in _createDialog
  File "cura\CrashHandler.py", line 86 in __init__
  File "cura_app.py", line 169 in exceptHook
  File "UM\Qt\QtApplication.py", line 421 in exec
  File "cura\CuraApplication.py", line 958 in run
  File "cura_app.py", line 243 in <module>

**Comment by TristanHorlamus** [comment]
might be solved with https://github.com/mirdoc/Cura-CubePrinterPlugin/pull/15

**Comment by MattB783** [comment]
I had the same issue today with 5.11 and .cubex file for CubeX Duo.  I'm new to it though.  didn't work at all in 4.8.0, so upgraded to latest 5.11 and got same error shown above.  Slicer worked fine, just when trying to save.  Thank you for this great utility.  Anxious to try it out

**Comment by MattB783** [comment]
How do i get to the Solved #15?
Sorry, new to github as well

**Comment by mirdoc** [comment]
Sorry guys! Have just incorporated fixes and pushed release 0.2.6

**Comment by MattB783** [comment]
Thank you Mirdoc.  You’re awesome


Sent from Yahoo Mail for iPhone


On Saturday, January 3, 2026, 10:32 PM, mirdoc ***@***.***> wrote:

mirdoc left a comment (mirdoc/Cura-CubePrinterPlugin#14)
Sorry guys! Have just incorporated fixes and pushed release 0.2.6
